max-autominers: 1

upgrades:
#key drop chance in %
  key-max-level: 5
  key-drop:
    level-1: 1
    level-2: 2
    level-3: 5
    level-4: 10
    level-5: 20

#key upgrade price
  key-price:
    level-2: 100
    level-3: 1000
    level-4: 10000
    level-5: 100000

  token-max-level: 5
#token drop chance in %
  token-drop:
    level-1: 1
    level-2: 2
    level-3: 5
    level-4: 10
    level-5: 20

#key upgrade price
  token-price:
    level-2: 100
    level-3: 1000
    level-4: 10000
    level-5: 100000
